//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.21 at 10:57:16 AM IST 
//


package com.crypto.forex.parse;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation
 * for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ExchangeApiDefObjectFactory {


    /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes
   * for package:
   * 
   */
    public ExchangeApiDefObjectFactory() {
    }

    /**
     * Create an instance of {@link ExchangeApiDef }
     * 
     */
  public static ExchangeApiDef createExchangeApiDef() {
        return new ExchangeApiDef();
    }

    /**
     * Create an instance of {@link ExchangeApiDef.Price }
     * 
     */
  public static ExchangeApiDef.Price createExchangeApiDefPrice() {
        return new ExchangeApiDef.Price();
    }

    /**
     * Create an instance of {@link ExchangeApiDef.Metadata }
     * 
     */
  public static ExchangeApiDef.Metadata createExchangeApiDefMetadata() {
        return new ExchangeApiDef.Metadata();
    }

    /**
     * Create an instance of {@link ExchangeApiDef.BaseCoin }
     * 
     */
  public static ExchangeApiDef.BaseCoin createExchangeApiDefBaseCoin() {
        return new ExchangeApiDef.BaseCoin();
    }

    /**
     * Create an instance of {@link ExchangeApiDef.PeggedCoin }
     * 
     */
  public static ExchangeApiDef.PeggedCoin createExchangeApiDefPeggedCoin() {
        return new ExchangeApiDef.PeggedCoin();
    }

    /**
   * Create an instance of {@link .Operation }
   * 
   */
  public static Operation createOperation() {
    return new Operation();
    }

    /**
     * Create an instance of {@link ExchangeApiDef.Price.Operation }
     * 
     */
  public static ExchangeApiDef.Price.Operation createExchangeApiDefPriceOperation() {
        return new ExchangeApiDef.Price.Operation();
    }

    /**
     * Create an instance of {@link ExchangeApiDef.Metadata.QueryParams }
     * 
     */
  public static ExchangeApiDef.Metadata.QueryParams createExchangeApiDefMetadataQueryParams() {
        return new ExchangeApiDef.Metadata.QueryParams();
    }

}
