//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:55:02 PM IST 
//


package com.crypto.forex.parse;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.crypto.forex.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ExchangeApiDefObjectFactory2 {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.crypto.forex.jaxb
     * 
     */
    public ExchangeApiDefObjectFactory2() {
    }

    /**
     * Create an instance of {@link ExchangeApiDef2 }
     * 
     */
  public static ExchangeApiDef2 createExchangeDef() {
        return new ExchangeApiDef2();
    }

    /**
     * Create an instance of {@link ExchangeApiDef2.PeggedCoin }
     * 
     */
  public static ExchangeApiDef2.PeggedCoin createExchangeDefPeggedCoin() {
        return new ExchangeApiDef2.PeggedCoin();
    }

    /**
     * Create an instance of {@link ExchangeApiDef2.BaseCoin }
     * 
     */
  public static ExchangeApiDef2.BaseCoin createExchangeDefBaseCoin() {
        return new ExchangeApiDef2.BaseCoin();
    }

    /**
     * Create an instance of {@link ExchangeApiDef2.Price }
     * 
     */
  public static ExchangeApiDef2.Price createExchangeDefPrice() {
        return new ExchangeApiDef2.Price();
    }

    /**
     * Create an instance of {@link ExchangeApiDef2.Metadata }
     * 
     */
  public static ExchangeApiDef2.Metadata createExchangeDefMetadata() {
        return new ExchangeApiDef2.Metadata();
    }

    /**
     * Create an instance of {@link ExchangeApiDef2.PeggedCoin.Operation }
     * 
     */
  public static ExchangeApiDef2.PeggedCoin.Operation createExchangeDefPeggedCoinOperation() {
        return new ExchangeApiDef2.PeggedCoin.Operation();
    }

    /**
     * Create an instance of {@link ExchangeApiDef2.BaseCoin.Operation }
     * 
     */
  public static ExchangeApiDef2.BaseCoin.Operation createExchangeDefBaseCoinOperation() {
        return new ExchangeApiDef2.BaseCoin.Operation();
    }

    /**
     * Create an instance of {@link ExchangeApiDef2.Price.Operation }
     * 
     */
  public static ExchangeApiDef2.Price.Operation createExchangeDefPriceOperation() {
        return new ExchangeApiDef2.Price.Operation();
    }

    /**
     * Create an instance of {@link ExchangeApiDef2.Metadata.QueryParams }
     * 
     */
  public static ExchangeApiDef2.Metadata.QueryParams createExchangeDefMetadataQueryParams() {
        return new ExchangeApiDef2.Metadata.QueryParams();
    }

}
