package com.crypto.forex.parse;
//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2018.03.19 at 09:35:46 AM IST 
//


import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
* <p>Java class for anonymous complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType>
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="baseUri" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="priceUri" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="metadata">
*           &lt;complexType>
*             &lt;complexContent>
*               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                 &lt;sequence>
*                   &lt;element name="apiMethod" type="{http://www.w3.org/2001/XMLSchema}string"/>
*                   &lt;element name="queryParams">
*                     &lt;complexType>
*                       &lt;complexContent>
*                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
*                         &lt;/restriction>
*                       &lt;/complexContent>
*                     &lt;/complexType>
*                   &lt;/element>
*                 &lt;/sequence>
*               &lt;/restriction>
*             &lt;/complexContent>
*           &lt;/complexType>
*         &lt;/element>
*         &lt;element name="price">
*           &lt;complexType>
*             &lt;complexContent>
*               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                 &lt;sequence>
*                   &lt;element name="attr_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
*                   &lt;element name="operation" maxOccurs="unbounded">
*                     &lt;complexType>
*                       &lt;complexContent>
*                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                           &lt;sequence>
*                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
*                             &lt;element name="args" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded"/>
*                           &lt;/sequence>
*                         &lt;/restriction>
*                       &lt;/complexContent>
*                     &lt;/complexType>
*                   &lt;/element>
*                 &lt;/sequence>
*               &lt;/restriction>
*             &lt;/complexContent>
*           &lt;/complexType>
*         &lt;/element>
*         &lt;element name="baseCoin">
*           &lt;complexType>
*             &lt;complexContent>
*               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                 &lt;sequence>
*                   &lt;element name="attr_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
*                   &lt;element name="operation" maxOccurs="unbounded">
*                     &lt;complexType>
*                       &lt;complexContent>
*                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                           &lt;sequence>
*                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
*                             &lt;element name="args" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded"/>
*                           &lt;/sequence>
*                         &lt;/restriction>
*                       &lt;/complexContent>
*                     &lt;/complexType>
*                   &lt;/element>
*                 &lt;/sequence>
*               &lt;/restriction>
*             &lt;/complexContent>
*           &lt;/complexType>
*         &lt;/element>
*         &lt;element name="peggedCoin">
*           &lt;complexType>
*             &lt;complexContent>
*               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                 &lt;sequence>
*                   &lt;element name="attr_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
*                   &lt;element name="operation" maxOccurs="unbounded">
*                     &lt;complexType>
*                       &lt;complexContent>
*                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                           &lt;sequence>
*                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
*                             &lt;element name="args" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded"/>
*                           &lt;/sequence>
*                         &lt;/restriction>
*                       &lt;/complexContent>
*                     &lt;/complexType>
*                   &lt;/element>
*                 &lt;/sequence>
*               &lt;/restriction>
*             &lt;/complexContent>
*           &lt;/complexType>
*         &lt;/element>
*       &lt;/sequence>
*       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
 "type",
 "baseUri",
 "priceUri",
 "metadata",
 "price",
 "baseCoin",
 "peggedCoin"
})
@XmlRootElement(name = "Exchange", namespace = "urn:Crypto.Forex")
public class ExchangeApi implements ExchangeParseDef{

 @XmlElement(required = true)
 protected String type;
 @XmlElement(required = true)
 protected String baseUri;
 @XmlElement(required = true)
 protected String priceUri;
 @XmlElement(required = true)
 protected ExchangeApi.Metadata metadata;
 @XmlElement(required = true)
 protected ExchangeApi.Price price;
 @XmlElement(required = true)
 protected ExchangeApi.BaseCoin baseCoin;
 @XmlElement(required = true)
 protected ExchangeApi.PeggedCoin peggedCoin;
 @XmlAttribute(name = "name")
 protected String name;

 /**
  * Gets the value of the type property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getType() {
     return type;
 }

 /**
  * Sets the value of the type property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setType(String value) {
     this.type = value;
 }

 /**
  * Gets the value of the baseUri property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getBaseUri() {
     return baseUri;
 }

 /**
  * Sets the value of the baseUri property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setBaseUri(String value) {
     this.baseUri = value;
 }

 /**
  * Gets the value of the priceUri property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getPriceUri() {
     return priceUri;
 }

 /**
  * Sets the value of the priceUri property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setPriceUri(String value) {
     this.priceUri = value;
 }

 /**
  * Gets the value of the metadata property.
  * 
  * @return
  *     possible object is
  *     {@link ExchangeApi.Metadata }
  *     
  */
 public ExchangeApi.Metadata getMetadata() {
     return metadata;
 }

 /**
  * Sets the value of the metadata property.
  * 
  * @param value
  *     allowed object is
  *     {@link ExchangeApi.Metadata }
  *     
  */
 public void setMetadata(ExchangeApi.Metadata value) {
     this.metadata = value;
 }

 /**
  * Gets the value of the price property.
  * 
  * @return
  *     possible object is
  *     {@link ExchangeApi.Price }
  *     
  */
 public ExchangeApi.Price getPrice() {
     return price;
 }

 /**
  * Sets the value of the price property.
  * 
  * @param value
  *     allowed object is
  *     {@link ExchangeApi.Price }
  *     
  */
 public void setPrice(ExchangeApi.Price value) {
     this.price = value;
 }

 /**
  * Gets the value of the baseCoin property.
  * 
  * @return
  *     possible object is
  *     {@link ExchangeApi.BaseCoin }
  *     
  */
 public ExchangeApi.BaseCoin getBaseCoin() {
     return baseCoin;
 }

 /**
  * Sets the value of the baseCoin property.
  * 
  * @param value
  *     allowed object is
  *     {@link ExchangeApi.BaseCoin }
  *     
  */
 public void setBaseCoin(ExchangeApi.BaseCoin value) {
     this.baseCoin = value;
 }

 /**
  * Gets the value of the peggedCoin property.
  * 
  * @return
  *     possible object is
  *     {@link ExchangeApi.PeggedCoin }
  *     
  */
 public ExchangeApi.PeggedCoin getPeggedCoin() {
     return peggedCoin;
 }

 /**
  * Sets the value of the peggedCoin property.
  * 
  * @param value
  *     allowed object is
  *     {@link ExchangeApi.PeggedCoin }
  *     
  */
 public void setPeggedCoin(ExchangeApi.PeggedCoin value) {
     this.peggedCoin = value;
 }

 /**
  * Gets the value of the name property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getName() {
     return name;
 }

 /**
  * Sets the value of the name property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setName(String value) {
     this.name = value;
 }


 /**
  * <p>Java class for anonymous complex type.
  * 
  * <p>The following schema fragment specifies the expected content contained within this class.
  * 
  * <pre>
  * &lt;complexType>
  *   &lt;complexContent>
  *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *       &lt;sequence>
  *         &lt;element name="attr_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
  *         &lt;element name="operation" maxOccurs="unbounded">
  *           &lt;complexType>
  *             &lt;complexContent>
  *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *                 &lt;sequence>
  *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
  *                   &lt;element name="args" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded"/>
  *                 &lt;/sequence>
  *               &lt;/restriction>
  *             &lt;/complexContent>
  *           &lt;/complexType>
  *         &lt;/element>
  *       &lt;/sequence>
  *     &lt;/restriction>
  *   &lt;/complexContent>
  * &lt;/complexType>
  * </pre>
  * 
  * 
  */
 @XmlAccessorType(XmlAccessType.FIELD)
 @XmlType(name = "", propOrder = {
     "attrName",
     "operation"
 })
 public static class BaseCoin {

     @XmlElement(name = "attr_name", required = true)
     protected String attrName;
     @XmlElement(required = true)
     protected List<ExchangeApi.BaseCoin.Operation> operation;

     /**
      * Gets the value of the attrName property.
      * 
      * @return
      *     possible object is
      *     {@link String }
      *     
      */
     public String getAttrName() {
         return attrName;
     }

     /**
      * Sets the value of the attrName property.
      * 
      * @param value
      *     allowed object is
      *     {@link String }
      *     
      */
     public void setAttrName(String value) {
         this.attrName = value;
     }

     /**
      * Gets the value of the operation property.
      * 
      * <p>
      * This accessor method returns a reference to the live list,
      * not a snapshot. Therefore any modification you make to the
      * returned list will be present inside the JAXB object.
      * This is why there is not a <CODE>set</CODE> method for the operation property.
      * 
      * <p>
      * For example, to add a new item, do as follows:
      * <pre>
      *    getOperation().add(newItem);
      * </pre>
      * 
      * 
      * <p>
      * Objects of the following type(s) are allowed in the list
      * {@link ExchangeApi.BaseCoin.Operation }
      * 
      * 
      */
     public List<ExchangeApi.BaseCoin.Operation> getOperation() {
         if (operation == null) {
             operation = new ArrayList<ExchangeApi.BaseCoin.Operation>();
         }
         return this.operation;
     }


     /**
      * <p>Java class for anonymous complex type.
      * 
      * <p>The following schema fragment specifies the expected content contained within this class.
      * 
      * <pre>
      * &lt;complexType>
      *   &lt;complexContent>
      *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
      *       &lt;sequence>
      *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
      *         &lt;element name="args" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded"/>
      *       &lt;/sequence>
      *     &lt;/restriction>
      *   &lt;/complexContent>
      * &lt;/complexType>
      * </pre>
      * 
      * 
      */
     @XmlAccessorType(XmlAccessType.FIELD)
     @XmlType(name = "", propOrder = {
         "name",
         "args"
     })
     public static class Operation {

         @XmlElement(required = true)
         protected String name;
         @XmlElement(required = true)
         protected List<Object> args;

         /**
          * Gets the value of the name property.
          * 
          * @return
          *     possible object is
          *     {@link String }
          *     
          */
         public String getName() {
             return name;
         }

         /**
          * Sets the value of the name property.
          * 
          * @param value
          *     allowed object is
          *     {@link String }
          *     
          */
         public void setName(String value) {
             this.name = value;
         }

         /**
          * Gets the value of the args property.
          * 
          * <p>
          * This accessor method returns a reference to the live list,
          * not a snapshot. Therefore any modification you make to the
          * returned list will be present inside the JAXB object.
          * This is why there is not a <CODE>set</CODE> method for the args property.
          * 
          * <p>
          * For example, to add a new item, do as follows:
          * <pre>
          *    getArgs().add(newItem);
          * </pre>
          * 
          * 
          * <p>
          * Objects of the following type(s) are allowed in the list
          * {@link Object }
          * 
          * 
          */
         public List<Object> getArgs() {
             if (args == null) {
                 args = new ArrayList<Object>();
             }
             return this.args;
         }

     }

 }


 /**
  * <p>Java class for anonymous complex type.
  * 
  * <p>The following schema fragment specifies the expected content contained within this class.
  * 
  * <pre>
  * &lt;complexType>
  *   &lt;complexContent>
  *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *       &lt;sequence>
  *         &lt;element name="apiMethod" type="{http://www.w3.org/2001/XMLSchema}string"/>
  *         &lt;element name="queryParams">
  *           &lt;complexType>
  *             &lt;complexContent>
  *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
  *               &lt;/restriction>
  *             &lt;/complexContent>
  *           &lt;/complexType>
  *         &lt;/element>
  *       &lt;/sequence>
  *     &lt;/restriction>
  *   &lt;/complexContent>
  * &lt;/complexType>
  * </pre>
  * 
  * 
  */
 @XmlAccessorType(XmlAccessType.FIELD)
 @XmlType(name = "", propOrder = {
     "apiMethod",
     "queryParams"
 })
 public static class Metadata {

     @XmlElement(required = true)
     protected String apiMethod;
     @XmlElement(required = true)
     protected ExchangeApi.Metadata.QueryParams queryParams;

     /**
      * Gets the value of the apiMethod property.
      * 
      * @return
      *     possible object is
      *     {@link String }
      *     
      */
     public String getApiMethod() {
         return apiMethod;
     }

     /**
      * Sets the value of the apiMethod property.
      * 
      * @param value
      *     allowed object is
      *     {@link String }
      *     
      */
     public void setApiMethod(String value) {
         this.apiMethod = value;
     }

     /**
      * Gets the value of the queryParams property.
      * 
      * @return
      *     possible object is
      *     {@link ExchangeApi.Metadata.QueryParams }
      *     
      */
     public ExchangeApi.Metadata.QueryParams getQueryParams() {
         return queryParams;
     }

     /**
      * Sets the value of the queryParams property.
      * 
      * @param value
      *     allowed object is
      *     {@link ExchangeApi.Metadata.QueryParams }
      *     
      */
     public void setQueryParams(ExchangeApi.Metadata.QueryParams value) {
         this.queryParams = value;
     }


     /**
      * <p>Java class for anonymous complex type.
      * 
      * <p>The following schema fragment specifies the expected content contained within this class.
      * 
      * <pre>
      * &lt;complexType>
      *   &lt;complexContent>
      *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
      *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
      *     &lt;/restriction>
      *   &lt;/complexContent>
      * &lt;/complexType>
      * </pre>
      * 
      * 
      */
     @XmlAccessorType(XmlAccessType.FIELD)
     @XmlType(name = "")
     public static class QueryParams {

         @XmlAttribute(name = "value")
         protected String value;

         /**
          * Gets the value of the value property.
          * 
          * @return
          *     possible object is
          *     {@link String }
          *     
          */
         public String getValue() {
             return value;
         }

         /**
          * Sets the value of the value property.
          * 
          * @param value
          *     allowed object is
          *     {@link String }
          *     
          */
         public void setValue(String value) {
             this.value = value;
         }

     }

 }


 /**
  * <p>Java class for anonymous complex type.
  * 
  * <p>The following schema fragment specifies the expected content contained within this class.
  * 
  * <pre>
  * &lt;complexType>
  *   &lt;complexContent>
  *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *       &lt;sequence>
  *         &lt;element name="attr_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
  *         &lt;element name="operation" maxOccurs="unbounded">
  *           &lt;complexType>
  *             &lt;complexContent>
  *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *                 &lt;sequence>
  *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
  *                   &lt;element name="args" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded"/>
  *                 &lt;/sequence>
  *               &lt;/restriction>
  *             &lt;/complexContent>
  *           &lt;/complexType>
  *         &lt;/element>
  *       &lt;/sequence>
  *     &lt;/restriction>
  *   &lt;/complexContent>
  * &lt;/complexType>
  * </pre>
  * 
  * 
  */
 @XmlAccessorType(XmlAccessType.FIELD)
 @XmlType(name = "", propOrder = {
     "attrName",
     "operation"
 })
 public static class PeggedCoin {

     @XmlElement(name = "attr_name", required = true)
     protected String attrName;
     @XmlElement(required = true)
     protected List<ExchangeApi.PeggedCoin.Operation> operation;

     /**
      * Gets the value of the attrName property.
      * 
      * @return
      *     possible object is
      *     {@link String }
      *     
      */
     public String getAttrName() {
         return attrName;
     }

     /**
      * Sets the value of the attrName property.
      * 
      * @param value
      *     allowed object is
      *     {@link String }
      *     
      */
     public void setAttrName(String value) {
         this.attrName = value;
     }

     /**
      * Gets the value of the operation property.
      * 
      * <p>
      * This accessor method returns a reference to the live list,
      * not a snapshot. Therefore any modification you make to the
      * returned list will be present inside the JAXB object.
      * This is why there is not a <CODE>set</CODE> method for the operation property.
      * 
      * <p>
      * For example, to add a new item, do as follows:
      * <pre>
      *    getOperation().add(newItem);
      * </pre>
      * 
      * 
      * <p>
      * Objects of the following type(s) are allowed in the list
      * {@link ExchangeApi.PeggedCoin.Operation }
      * 
      * 
      */
     public List<ExchangeApi.PeggedCoin.Operation> getOperation() {
         if (operation == null) {
             operation = new ArrayList<ExchangeApi.PeggedCoin.Operation>();
         }
         return this.operation;
     }


     /**
      * <p>Java class for anonymous complex type.
      * 
      * <p>The following schema fragment specifies the expected content contained within this class.
      * 
      * <pre>
      * &lt;complexType>
      *   &lt;complexContent>
      *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
      *       &lt;sequence>
      *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
      *         &lt;element name="args" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded"/>
      *       &lt;/sequence>
      *     &lt;/restriction>
      *   &lt;/complexContent>
      * &lt;/complexType>
      * </pre>
      * 
      * 
      */
     @XmlAccessorType(XmlAccessType.FIELD)
     @XmlType(name = "", propOrder = {
         "name",
         "args"
     })
     public static class Operation {

         @XmlElement(required = true)
         protected String name;
         @XmlElement(required = true)
         protected List<Object> args;

         /**
          * Gets the value of the name property.
          * 
          * @return
          *     possible object is
          *     {@link String }
          *     
          */
         public String getName() {
             return name;
         }

         /**
          * Sets the value of the name property.
          * 
          * @param value
          *     allowed object is
          *     {@link String }
          *     
          */
         public void setName(String value) {
             this.name = value;
         }

         /**
          * Gets the value of the args property.
          * 
          * <p>
          * This accessor method returns a reference to the live list,
          * not a snapshot. Therefore any modification you make to the
          * returned list will be present inside the JAXB object.
          * This is why there is not a <CODE>set</CODE> method for the args property.
          * 
          * <p>
          * For example, to add a new item, do as follows:
          * <pre>
          *    getArgs().add(newItem);
          * </pre>
          * 
          * 
          * <p>
          * Objects of the following type(s) are allowed in the list
          * {@link Object }
          * 
          * 
          */
         public List<Object> getArgs() {
             if (args == null) {
                 args = new ArrayList<Object>();
             }
             return this.args;
         }

     }

 }


 /**
  * <p>Java class for anonymous complex type.
  * 
  * <p>The following schema fragment specifies the expected content contained within this class.
  * 
  * <pre>
  * &lt;complexType>
  *   &lt;complexContent>
  *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *       &lt;sequence>
  *         &lt;element name="attr_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
  *         &lt;element name="operation" maxOccurs="unbounded">
  *           &lt;complexType>
  *             &lt;complexContent>
  *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *                 &lt;sequence>
  *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
  *                   &lt;element name="args" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded"/>
  *                 &lt;/sequence>
  *               &lt;/restriction>
  *             &lt;/complexContent>
  *           &lt;/complexType>
  *         &lt;/element>
  *       &lt;/sequence>
  *     &lt;/restriction>
  *   &lt;/complexContent>
  * &lt;/complexType>
  * </pre>
  * 
  * 
  */
 @XmlAccessorType(XmlAccessType.FIELD)
 @XmlType(name = "", propOrder = {
     "attrName",
     "operation"
 })
 public static class Price {

     @XmlElement(name = "attr_name", required = true)
     protected String attrName;
     @XmlElement(required = true)
     protected List<ExchangeApi.Price.Operation> operation;

     /**
      * Gets the value of the attrName property.
      * 
      * @return
      *     possible object is
      *     {@link String }
      *     
      */
     public String getAttrName() {
         return attrName;
     }

     /**
      * Sets the value of the attrName property.
      * 
      * @param value
      *     allowed object is
      *     {@link String }
      *     
      */
     public void setAttrName(String value) {
         this.attrName = value;
     }

     /**
      * Gets the value of the operation property.
      * 
      * <p>
      * This accessor method returns a reference to the live list,
      * not a snapshot. Therefore any modification you make to the
      * returned list will be present inside the JAXB object.
      * This is why there is not a <CODE>set</CODE> method for the operation property.
      * 
      * <p>
      * For example, to add a new item, do as follows:
      * <pre>
      *    getOperation().add(newItem);
      * </pre>
      * 
      * 
      * <p>
      * Objects of the following type(s) are allowed in the list
      * {@link ExchangeApi.Price.Operation }
      * 
      * 
      */
     public List<ExchangeApi.Price.Operation> getOperation() {
         if (operation == null) {
             operation = new ArrayList<ExchangeApi.Price.Operation>();
         }
         return this.operation;
     }


     /**
      * <p>Java class for anonymous complex type.
      * 
      * <p>The following schema fragment specifies the expected content contained within this class.
      * 
      * <pre>
      * &lt;complexType>
      *   &lt;complexContent>
      *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
      *       &lt;sequence>
      *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
      *         &lt;element name="args" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded"/>
      *       &lt;/sequence>
      *     &lt;/restriction>
      *   &lt;/complexContent>
      * &lt;/complexType>
      * </pre>
      * 
      * 
      */
     @XmlAccessorType(XmlAccessType.FIELD)
     @XmlType(name = "", propOrder = {
         "name",
         "args"
     })
     public static class Operation {

         @XmlElement(required = true)
         protected String name;
         @XmlElement(required = true)
         protected List<Object> args;

         /**
          * Gets the value of the name property.
          * 
          * @return
          *     possible object is
          *     {@link String }
          *     
          */
         public String getName() {
             return name;
         }

         /**
          * Sets the value of the name property.
          * 
          * @param value
          *     allowed object is
          *     {@link String }
          *     
          */
         public void setName(String value) {
             this.name = value;
         }

         /**
          * Gets the value of the args property.
          * 
          * <p>
          * This accessor method returns a reference to the live list,
          * not a snapshot. Therefore any modification you make to the
          * returned list will be present inside the JAXB object.
          * This is why there is not a <CODE>set</CODE> method for the args property.
          * 
          * <p>
          * For example, to add a new item, do as follows:
          * <pre>
          *    getArgs().add(newItem);
          * </pre>
          * 
          * 
          * <p>
          * Objects of the following type(s) are allowed in the list
          * {@link Object }
          * 
          * 
          */
         public List<Object> getArgs() {
             if (args == null) {
                 args = new ArrayList<Object>();
             }
             return this.args;
         }

     }

 }

}
