//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.21 at 10:57:16 AM IST 
//


package com.crypto.forex.parse;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="baseUri" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="priceUri" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="metadata">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="apiMethod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="queryParams">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="price">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attr_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="operation" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="args" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="baseCoin">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attr_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element ref="{urn:Crypto.Forex}operation" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="peggedCoin">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attr_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element ref="{urn:Crypto.Forex}operation" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="exchange" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "type",
    "baseUri",
    "priceUri",
    "metadata",
    "price",
    "baseCoin",
    "peggedCoin"
}, factoryClass = ExchangeApiDefObjectFactory.class, factoryMethod = "createExchangeApiDef")
@XmlRootElement(name = "ExchangeApiDef")
public class ExchangeApiDef implements ExchangeParseDef {

    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected String baseUri;
    @XmlElement(required = true)
    protected String priceUri;
    @XmlElement(required = true)
    protected ExchangeApiDef.Metadata metadata;
    @XmlElement(required = true)
    protected ExchangeApiDef.Price price;
    @XmlElement(required = true)
    protected ExchangeApiDef.BaseCoin baseCoin;
    @XmlElement(required = true)
    protected ExchangeApiDef.PeggedCoin peggedCoin;
    @XmlAttribute(name = "exchange")
    protected String exchange;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(final String value) {
        this.type = value;
    }

    /**
     * Gets the value of the baseUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseUri() {
        return baseUri;
    }

    /**
     * Sets the value of the baseUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseUri(final String value) {
        this.baseUri = value;
    }

    /**
     * Gets the value of the priceUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceUri() {
        return priceUri;
    }

    /**
     * Sets the value of the priceUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceUri(final String value) {
        this.priceUri = value;
    }

    /**
     * Gets the value of the metadata property.
     * 
     * @return
     *     possible object is
     *     {@link ExchangeApiDef.Metadata }
     *     
     */
    public ExchangeApiDef.Metadata getMetadata() {
        return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExchangeApiDef.Metadata }
     *     
     */
    public void setMetadata(final ExchangeApiDef.Metadata value) {
        this.metadata = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link ExchangeApiDef.Price }
     *     
     */
    public ExchangeApiDef.Price getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExchangeApiDef.Price }
     *     
     */
    public void setPrice(final ExchangeApiDef.Price value) {
        this.price = value;
    }

    /**
     * Gets the value of the baseCoin property.
     * 
     * @return
     *     possible object is
     *     {@link ExchangeApiDef.BaseCoin }
     *     
     */
    public ExchangeApiDef.BaseCoin getBaseCoin() {
        return baseCoin;
    }

    /**
     * Sets the value of the baseCoin property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExchangeApiDef.BaseCoin }
     *     
     */
    public void setBaseCoin(final ExchangeApiDef.BaseCoin value) {
        this.baseCoin = value;
    }

    /**
     * Gets the value of the peggedCoin property.
     * 
     * @return
     *     possible object is
     *     {@link ExchangeApiDef.PeggedCoin }
     *     
     */
    public ExchangeApiDef.PeggedCoin getPeggedCoin() {
        return peggedCoin;
    }

    /**
     * Sets the value of the peggedCoin property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExchangeApiDef.PeggedCoin }
     *     
     */
    public void setPeggedCoin(final ExchangeApiDef.PeggedCoin value) {
        this.peggedCoin = value;
    }

    /**
     * Gets the value of the exchange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
  @Override
    public String getExchange() {
        return exchange;
    }

    /**
     * Sets the value of the exchange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExchange(final String value) {
        this.exchange = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attr_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element ref="{urn:Crypto.Forex}operation" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attrName",
        "operation"
    })
    public static class BaseCoin {

        @XmlElement(name = "attr_name", required = true)
        protected String attrName;
        @XmlElement(namespace = "urn:Crypto.Forex", required = true)
    protected List<Operation> operation;

        /**
         * Gets the value of the attrName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttrName() {
            return attrName;
        }

        /**
         * Sets the value of the attrName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttrName(final String value) {
            this.attrName = value;
        }

        /**
     * Gets the value of the operation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the operation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getOperation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Operation }
     * 
     * 
     */
    public List<Operation> getOperation() {
            if (operation == null) {
        operation = new ArrayList<Operation>();
            }
            return this.operation;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="apiMethod" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="queryParams">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "apiMethod",
        "queryParams"
    })
    public static class Metadata {

        @XmlElement(required = true)
        protected String apiMethod;
        @XmlElement(required = true)
        protected ExchangeApiDef.Metadata.QueryParams queryParams;

        /**
         * Gets the value of the apiMethod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApiMethod() {
            return apiMethod;
        }

        /**
         * Sets the value of the apiMethod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApiMethod(final String value) {
            this.apiMethod = value;
        }

        /**
         * Gets the value of the queryParams property.
         * 
         * @return
         *     possible object is
         *     {@link ExchangeApiDef.Metadata.QueryParams }
         *     
         */
        public ExchangeApiDef.Metadata.QueryParams getQueryParams() {
            return queryParams;
        }

        /**
         * Sets the value of the queryParams property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExchangeApiDef.Metadata.QueryParams }
         *     
         */
        public void setQueryParams(final ExchangeApiDef.Metadata.QueryParams value) {
            this.queryParams = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class QueryParams {

            @XmlAttribute(name = "value")
            protected String value;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(final String value) {
                this.value = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attr_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element ref="{urn:Crypto.Forex}operation" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attrName",
        "operation"
    })
    public static class PeggedCoin {

        @XmlElement(name = "attr_name", required = true)
        protected String attrName;
        @XmlElement(namespace = "urn:Crypto.Forex", required = true)
    protected List<Operation> operation;

        /**
         * Gets the value of the attrName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttrName() {
            return attrName;
        }

        /**
         * Sets the value of the attrName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttrName(final String value) {
            this.attrName = value;
        }

        /**
     * Gets the value of the operation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the operation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getOperation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Operation }
     * 
     * 
     */
    public List<Operation> getOperation() {
            if (operation == null) {
        operation = new ArrayList<Operation>();
            }
            return this.operation;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attr_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="operation" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="args" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attrName",
        "operation"
    })
    public static class Price {

        @XmlElement(name = "attr_name", required = true)
        protected String attrName;
        @XmlElement(required = true)
        protected List<ExchangeApiDef.Price.Operation> operation;

        /**
         * Gets the value of the attrName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttrName() {
            return attrName;
        }

        /**
         * Sets the value of the attrName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttrName(final String value) {
            this.attrName = value;
        }

        /**
         * Gets the value of the operation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the operation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOperation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ExchangeApiDef.Price.Operation }
         * 
         * 
         */
        public List<ExchangeApiDef.Price.Operation> getOperation() {
            if (operation == null) {
                operation = new ArrayList<ExchangeApiDef.Price.Operation>();
            }
            return this.operation;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="args" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "args"
        })
        public static class Operation {

            @XmlElement(required = true)
            protected String name;
      @XmlElement()
      protected List<String> args;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(final String value) {
                this.name = value;
            }

            /**
             * Gets the value of the args property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the args property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getArgs().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Object }
             * 
             * 
             */
      public List<String> getArgs() {
                if (args == null) {
          args = new ArrayList<String>();
                }
                return this.args;
            }

        }

    }

}
