//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 07:55:02 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:Crypto.Forex",
    elementFormDefault = XmlNsForm.QUALIFIED)
package com.crypto.forex.parse;

import javax.xml.bind.annotation.XmlNsForm;
